version: "3.7"
services:
  browser:
    image: browserless/chrome:1.47-chrome-stable
    environment:
      - MAX_CONCURRENT_SESSIONS=5
      - CONNECTION_TIMEOUT=-1
    expose:
      - "3000"
  whatsapp:
    build: 
      context: .
    image: whatsapp:1.0
    ports: 
      - "1000:5000"
    command: sh -c './wait-for.sh browser:3000 -- npm start'
    depends_on: 
      - browser